# Generated by Django 2.1.1 on 2018-09-30 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnagagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facilitator', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('semester', models.CharField(max_length=255)),
                ('total_uno_students', models.IntegerField()),
                ('total_uno_hrs', models.CharField(max_length=20)),
                ('total_k12_students', models.IntegerField(null=True)),
                ('total_k12_hrs', models.CharField(max_length=10)),
                ('total_uno_faculty', models.IntegerField(blank=True)),
                ('total_other_community_members', models.IntegerField(blank=True)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('other_details', models.CharField(blank=True, max_length=100)),
                ('outcomes', models.CharField(blank=True, max_length=100)),
                ('total_economic_impact', models.DecimalField(blank=True, decimal_places=4, max_digits=15)),
                ('address_line1', models.CharField(blank=True, max_length=1024)),
                ('address_line2', models.CharField(blank=True, max_length=1024)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('Zip', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ActivityType')),
                ('engagement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.EnagagementType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCampusPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hours', models.IntegerField(blank=True, null=True)),
                ('no_people', models.IntegerField(blank=True, null=True)),
                ('wages', models.IntegerField(blank=True, null=True)),
                ('campus_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCommunityPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hours', models.IntegerField(blank=True, null=True)),
                ('no_people', models.IntegerField(blank=True, null=True)),
                ('wages', models.IntegerField(blank=True, null=True)),
                ('community_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(max_length=20)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MissionArea')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Status'),
        ),
    ]
