# Generated by Django 2.1.1 on 2018-09-25 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100)),
                ('engagementType', models.CharField(max_length=20)),
                ('activityType', models.CharField(max_length=20)),
                ('facilitator', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('semester', models.CharField(max_length=20)),
                ('totalNumUnoStudents', models.IntegerField()),
                ('totalUnoHours', models.CharField(max_length=20)),
                ('totalNumK12Students', models.IntegerField()),
                ('totalK12Hours', models.CharField(max_length=10)),
                ('numUnoFacultyStaff', models.IntegerField(blank=True)),
                ('numOtherCommunityMembers', models.IntegerField(blank=True)),
                ('startDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('otherDetails', models.CharField(blank=True, max_length=100)),
                ('outcomes', models.CharField(blank=True, max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('totalEconomicImpact', models.DecimalField(blank=True, decimal_places=4, max_digits=15)),
                ('address_line1', models.CharField(blank=True, max_length=1024)),
                ('address_line2', models.CharField(blank=True, max_length=1024)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('Zip', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hours', models.IntegerField(blank=True, null=True)),
                ('no_people', models.IntegerField(blank=True, null=True)),
                ('wages', models.IntegerField(blank=True, null=True)),
                ('CampuspartnerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner')),
                ('CommunityPartnerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner')),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
