# Generated by Django 2.1.1 on 2018-11-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(default='Training/Workshop/presentation', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectmission',
            name='mission_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Other', 'Other')], max_length=20),
        ),
    ]
