# Generated by Django 2.1.1 on 2018-10-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='project',
            new_name='name',
        ),
    ]
