# Generated by Django 2.1.1 on 2018-09-16 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='otherDetails',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalEconomicImpact',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalNumUnoStudents',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalUnoHours',
            field=models.CharField(max_length=20),
        ),
    ]
