# Generated by Django 2.1.1 on 2018-10-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='total_hours',
            new_name='uno_hours',
        ),
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='total_people',
            new_name='uno_people',
        ),
    ]
