# Generated by Django 2.1.1 on 2018-10-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnagagementType',
            new_name='EngagementType',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Zip',
        ),
        migrations.AddField(
            model_name='project',
            name='zip',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_economic_impact',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
