# Generated by Django 2.1.1 on 2018-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcampuspartner',
            name='total_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectcampuspartner',
            name='total_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
