# Generated by Django 2.1.1 on 2018-10-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181002_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='project',
            new_name='project_name',
        ),
    ]
