# Generated by Django 2.1.1 on 2018-09-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180916_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmission',
            name='mission_code',
        ),
    ]
