# Generated by Django 2.1.1 on 2018-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181009_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='uno_people',
            new_name='uno_students',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='total_hours',
            new_name='community_hours',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='total_people',
            new_name='community_members',
        ),
    ]
