# Generated by Django 2.1.1 on 2018-10-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_k12_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_uno_hours',
            field=models.IntegerField(),
        ),
    ]
