# Generated by Django 2.1.1 on 2019-04-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalacademicyear_historicalactivitytype_historicalengagementtype_historicalproject_historicalp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='end_academic_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.AcademicYear'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_academic_years', to='projects.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='end_semester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_semester',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
