# Generated by Django 2.1.1 on 2018-10-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180930_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_k12_hrs',
            new_name='total_k12_hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_uno_hrs',
            new_name='total_uno_hours',
        ),
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='no_hours',
            new_name='total_hours',
        ),
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='no_people',
            new_name='total_people',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='no_hours',
            new_name='total_hours',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='no_people',
            new_name='total_people',
        ),
        migrations.AlterField(
            model_name='project',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
