# Generated by Django 2.1.1 on 2018-10-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181009_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='uno_hours',
            new_name='total_hours',
        ),
        migrations.RenameField(
            model_name='projectcampuspartner',
            old_name='uno_students',
            new_name='total_people',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='community_hours',
            new_name='total_hours',
        ),
        migrations.RenameField(
            model_name='projectcommunitypartner',
            old_name='community_members',
            new_name='total_people',
        ),
    ]
