# Generated by Django 2.1.1 on 2018-11-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181024_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_k12_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_uno_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
