# Generated by Django 2.1.1 on 2018-10-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181028_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='description',
            field=models.CharField(default=-1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
