# Generated by Django 2.1.1 on 2019-04-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190407_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year1', to='projects.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_year2', to='projects.AcademicYear'),
        ),
    ]
