# Generated by Django 2.1.1 on 2018-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181204_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_semester',
            field=models.CharField(default='fall', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
