# Generated by Django 2.1.1 on 2019-04-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190407_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_year2', to='projects.AcademicYear'),
        ),
    ]
