# Generated by Django 2.1.1 on 2019-10-03 19:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190925_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='lead_faculty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_faculty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ActivityType'),
        ),
    ]
