# Generated by Django 2.1.1 on 2019-10-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191005_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmissionsubcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmissionsubcategory',
            name='secondary_mission_area',
        ),
        migrations.RemoveField(
            model_name='historicalmissionsubcategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='historicalprojectsubcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprojectsubcategory',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='historicalprojectsubcategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='missionsubcategory',
            name='secondary_mission_area',
        ),
        migrations.RemoveField(
            model_name='missionsubcategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='projectsubcategory',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projectsubcategory',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='HistoricalMissionSubCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectSubCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalSubCategory',
        ),
        migrations.DeleteModel(
            name='MissionSubCategory',
        ),
        migrations.DeleteModel(
            name='ProjectSubCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
