# Generated by Django 2.1.1 on 2019-10-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191005_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ActivityType'),
        ),
    ]
