# Generated by Django 2.1.1 on 2019-10-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20191007_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubcategory',
            name='sub_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
