# Generated by Django 2.1.1 on 2019-10-30 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_engagementactivitytype_historicalengagementactivitytype_historicalprojectengagementactivity_projecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='other_sub_category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Project', 'Project')], default='Project', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='recursive_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Projects_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='other_sub_category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Project', 'Project')], default='Project', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='recursive_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Projects_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
