# Generated by Django 2.1.1 on 2019-10-31 00:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20191030_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='other_sub_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_sub_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
    ]
