# Generated by Django 2.1.1 on 2019-11-01 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20191030_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='activity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.EngagementActivityType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.EngagementActivityType'),
        ),
    ]
