# Generated by Django 2.2.2 on 2019-11-09 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20191030_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='other_activity_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='project',
            name='other_activity_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
    ]
