# Generated by Django 2.2.2 on 2019-11-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20191109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcampuspartner',
            name='campus_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner'),
        ),
        migrations.AlterField(
            model_name='projectcommunitypartner',
            name='community_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner'),
        ),
        migrations.AlterField(
            model_name='projectmission',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.MissionArea'),
        ),
        migrations.AlterField(
            model_name='projectsubcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.SubCategory'),
        ),
    ]
