# Generated by Django 2.2.7 on 2019-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20191110_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='address_update_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='address_update_flag',
            field=models.BooleanField(default=False),
        ),
    ]
