# Generated by Django 2.2.7 on 2019-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20191206_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementtype',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalengagementtype',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
