# Generated by Django 4.1.1 on 2022-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_historicalcontact_options_and_more'),
        ('projects', '0019_alter_historicalacademicyear_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='mission_area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mission_area',
        ),
        migrations.AddField(
            model_name='project',
            name='mission_area',
            field=models.ManyToManyField(to='home.missionarea'),
        ),
    ]
