# Generated by Django 2.1.1 on 2018-09-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20180925_1902'),
        ('projects', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuspartner',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.College'),
        ),
        migrations.AddField(
            model_name='campuspartner',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.Department'),
        ),
        migrations.AddField(
            model_name='campuspartner',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.University'),
        ),
        migrations.AddField(
            model_name='campuspartneruser',
            name='campuspartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner'),
        ),
        migrations.AddField(
            model_name='campuspartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='college',
            name='University',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.University'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='communitytype',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitytype', to='partners.CommunityType'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='primary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='secondary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartneruser',
            name='communitypartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitypartner', to='partners.CommunityPartner'),
        ),
        migrations.AddField(
            model_name='communitypartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='projectName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.College'),
        ),
    ]
