# Generated by Django 2.1.1 on 2018-09-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('partners', '0001_initial'),
        ('home', '0002_contact_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='communitytype',
            name='partner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner'),
        ),
        migrations.AddField(
            model_name='communitypartnermission',
            name='mission_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartnermission',
            name='partner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner'),
        ),
    ]
