# Generated by Django 2.1.1 on 2018-09-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180925_1658'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.College')),
            ],
        ),
        migrations.RemoveField(
            model_name='university',
            name='college',
        ),
        migrations.RemoveField(
            model_name='university',
            name='department',
        ),
        migrations.AddField(
            model_name='campuspartneruser',
            name='campuspartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner'),
        ),
        migrations.AddField(
            model_name='campuspartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='communitytype',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitytype', to='partners.CommunityType'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='primary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='secondary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartneruser',
            name='communitypartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitypartner', to='partners.CommunityPartner'),
        ),
        migrations.AddField(
            model_name='communitypartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='projectName',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='college',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.University'),
        ),
        migrations.AddField(
            model_name='campuspartner',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.Department'),
        ),
    ]
