# Generated by Django 2.1.1 on 2018-09-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180926_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspartner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.University'),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.College'),
        ),
    ]
