# Generated by Django 2.1.1 on 2018-11-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', 'modelNameChange'),
        ('partners', '0002_auto_20181113_2052'),
    ]

    operations = [
    ]
