# Generated by Django 2.1.1 on 2018-09-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180925_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='k12_level',
            field=models.CharField(blank=True, help_text='If your community type is K12, Please provide the k12-level.', max_length=20),
        ),
    ]
