# Generated by Django 2.1.1 on 2018-11-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181116_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypartner',
            name='legislative_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='median_household_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartnermission',
            name='mission_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Other', 'Other')], default=False, max_length=20),
        ),
    ]
