# Generated by Django 2.1.1 on 2018-09-26 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20180925_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campuspartneruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='primary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_mission', to='home.MissionArea'),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='secondary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_mission', to='home.MissionArea'),
        ),
        migrations.AlterField(
            model_name='communitypartneruser',
            name='communitypartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitypartner', to='partners.CommunityPartner'),
        ),
    ]
