# Generated by Django 2.1.1 on 2018-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180915_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='college',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='k12_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
