# Generated by Django 2.1.1 on 2018-10-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180930_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypartner',
            old_name='Zip',
            new_name='zip',
        ),
    ]
