# Generated by Django 2.1.1 on 2018-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181013_2256'),
    ]

    operations = [
    ]
