# Generated by Django 2.1.1 on 2018-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181008_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
