# Generated by Django 2.0 on 2018-10-10 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_merge_20181009_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuspartner',
            name='college',
        ),
        migrations.AlterField(
            model_name='campuspartner',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.Department'),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='k12_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
