# Generated by Django 2.1.1 on 2018-10-04 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181003_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='community_type',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.CommunityType'),
        ),
    ]
