# Generated by Django 2.1.1 on 2018-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181125_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='website_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
