# Generated by Django 2.1.1 on 2018-10-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181002_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='k12_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
