# Generated by Django 2.1.1 on 2018-11-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181112_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='community_type',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.CommunityType', verbose_name='Community Type'),
        ),
    ]
