# Generated by Django 2.1.1 on 2018-10-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_merge_20181017_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspartner',
            name='education_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.EducationSystem'),
        ),
        migrations.AlterField(
            model_name='campuspartner',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.University'),
        ),
    ]
