# Generated by Django 2.1.1 on 2019-04-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_historicalcampuspartner_historicalcampuspartneruser_historicalcommunitypartner_historicalcommunitypa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuspartner',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='communitypartner',
            options={'ordering': ('name',)},
        ),
    ]
