# Generated by Django 2.1.1 on 2018-09-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20180915_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypartner',
            name='department',
        ),
    ]
