# Generated by Django 2.1.1 on 2018-10-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20181009_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campuspartner',
            old_name='college',
            new_name='college_name',
        ),
    ]
