# Generated by Django 2.1.1 on 2018-09-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_remove_communitypartner_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weitz_cec_part', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default=False, max_length=6)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.University')),
            ],
        ),
    ]
