# Generated by Django 2.1.1 on 2018-10-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20181003_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='weitz_cec_part',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=6),
        ),
    ]
