# Generated by Django 2.1.1 on 2019-10-19 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0004_auto_20190420_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartnerStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Partner Status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Partner Status',
                'verbose_name_plural': 'Partner Statuses',
            },
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='online_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommunitypartner',
            name='acronym',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunitypartner',
            name='online_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campuspartner',
            name='partner_status',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.PartnerStatus', verbose_name='Campus Partner Status'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='partner_status',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.PartnerStatus', verbose_name='Community Partner Status'),
        ),
        migrations.AddField(
            model_name='historicalcampuspartner',
            name='partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=30, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.PartnerStatus', verbose_name='Campus Partner Status'),
        ),
        migrations.AddField(
            model_name='historicalcommunitypartner',
            name='partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=30, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.PartnerStatus', verbose_name='Community Partner Status'),
        ),
    ]
