# Generated by Django 2.1.1 on 2019-10-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_engagementactivitytype_historicalengagementactivitytype_historicalprojectengagementactivity_projecte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0005_auto_20191019_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CecPartActiveYrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_semester', models.CharField(blank=True, choices=[('', '----------'), ('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('end_semester', models.CharField(blank=True, choices=[('', '----------'), ('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('camp_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner')),
                ('comm_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner')),
                ('end_acad_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cec_academic_year2', to='projects.AcademicYear')),
                ('start_acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cec_academic_year1', to='projects.AcademicYear')),
            ],
            options={
                'verbose_name': 'CEC Building Partner Active Year',
                'verbose_name_plural': 'CEC Building Partner Active Year',
            },
        ),
        migrations.CreateModel(
            name='CecPartnerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'CEC Partner Status',
                'verbose_name_plural': 'CEC Partner Statuses',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCecPartActiveYrs',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_semester', models.CharField(blank=True, choices=[('', '----------'), ('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('end_semester', models.CharField(blank=True, choices=[('', '----------'), ('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('camp_partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CampusPartner')),
                ('comm_partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CommunityPartner')),
                ('end_acad_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.AcademicYear')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('start_acad_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.AcademicYear')),
            ],
            options={
                'verbose_name': 'historical CEC Building Partner Active Year',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCecPartnerStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CEC Partner Status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='campuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CecPartnerStatus', verbose_name='Community CEC Partner Status'),
        ),
        migrations.AddField(
            model_name='historicalcampuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
        migrations.AddField(
            model_name='historicalcommunitypartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CecPartnerStatus', verbose_name='Community CEC Partner Status'),
        ),
    ]
