# Generated by Django 2.1.1 on 2018-09-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20180918_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuspartner',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
