# Generated by Django 2.1.1 on 2019-10-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20191021_1234'),
        ('partners', '0005_auto_20191024_1225'),
    ]

    operations = [
    ]
