# Generated by Django 2.1.1 on 2018-09-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_communitypartneruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartneruser',
            name='communitypartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitypartner', to='partners.CommunityPartner'),
        ),
    ]
