# Generated by Django 2.1.1 on 2018-09-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180924_1901'),
        ('partners', '0007_communitypartneruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypartnermission',
            name='mission_code',
        ),
        migrations.RemoveField(
            model_name='communitypartnermission',
            name='partner_name',
        ),
        migrations.RenameField(
            model_name='communitypartner',
            old_name='name',
            new_name='CommunityPartnerName',
        ),
        migrations.RemoveField(
            model_name='communitypartner',
            name='college',
        ),
        migrations.RemoveField(
            model_name='communitytype',
            name='partner_name',
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='Zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='communitytype',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communitytype', to='partners.CommunityType'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='primary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='secondary_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_mission', to='home.MissionArea'),
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='state',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='CommunityPartnerMission',
        ),
    ]
