# Generated by Django 2.2.1 on 2019-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20191023_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
