# Generated by Django 2.1.1 on 2019-11-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20191109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
