# Generated by Django 2.2.2 on 2019-11-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20191110_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CecPartnerStatus', verbose_name='Community CEC Partner Status'),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CecPartnerStatus', verbose_name='Community CEC Partner Status'),
        ),
    ]
