# Generated by Django 2.1.1 on 2018-09-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20180924_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='website_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
