# Generated by Django 2.2.7 on 2019-12-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20191115_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypartner',
            name='address_update_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommunitypartner',
            name='address_update_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
        migrations.AlterField(
            model_name='historicalcampuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
    ]
