# Generated by Django 2.2.7 on 2019-11-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20191115_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(default='Never', on_delete=django.db.models.deletion.CASCADE, to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
        migrations.AlterField(
            model_name='historicalcampuspartner',
            name='cec_partner_status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='Never', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.CecPartnerStatus', verbose_name='Campus CEC Partner Status'),
        ),
    ]
