# Generated by Django 4.1.1 on 2022-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20191206_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcampuspartner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical campus partner', 'verbose_name_plural': 'historical campus partners'},
        ),
        migrations.AlterModelOptions(
            name='historicalcampuspartneruser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical campus partner user', 'verbose_name_plural': 'historical campus partner users'},
        ),
        migrations.AlterModelOptions(
            name='historicalcecpartactiveyrs',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical CEC Building Partner Active Year', 'verbose_name_plural': 'historical CEC Building Partner Active Year'},
        ),
        migrations.AlterModelOptions(
            name='historicalcecpartnerstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical CEC Partner Status', 'verbose_name_plural': 'historical CEC Partner Statuses'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommunitypartner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical community partner', 'verbose_name_plural': 'historical community partners'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommunitypartnermission',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical community partner mission', 'verbose_name_plural': 'historical community partner missions'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommunitypartneruser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical community partner user', 'verbose_name_plural': 'historical community partner users'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommunitytype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical community type', 'verbose_name_plural': 'historical community types'},
        ),
        migrations.AlterModelOptions(
            name='historicalpartnerstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Partner Status', 'verbose_name_plural': 'historical Partner Statuses'},
        ),
        migrations.AlterField(
            model_name='campuspartner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcampuspartner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcampuspartner',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcampuspartneruser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcecpartactiveyrs',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcecpartnerstatus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartner',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartnermission',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitypartneruser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitytype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnerstatus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
