# Generated by Django 2.1 on 2018-09-08 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=15)),
                ('Zip', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('website_url', models.TextField()),
                ('college', models.CharField(max_length=50)),
                ('k12_level', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('weitz_cec_part', models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_type', models.CharField(max_length=20)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CommunityPartner')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('workphone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cellphone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contact_type', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=254)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CommunityPartner')),
            ],
        ),
        migrations.CreateModel(
            name='CPMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Missionarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_code', models.CharField(default=0, max_length=10)),
                ('mission_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engagement_type', models.CharField(max_length=20)),
                ('activity_type', models.CharField(max_length=20)),
                ('facilitator', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('semester', models.CharField(max_length=20)),
                ('no_uno_students', models.IntegerField()),
                ('hours_uno', models.CharField(max_length=20)),
                ('no_cp_members', models.IntegerField()),
                ('hours_cp', models.CharField(max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('details', models.CharField(max_length=100)),
                ('no_uno_faculty', models.IntegerField()),
                ('other_cp_members', models.IntegerField()),
                ('outcomes', models.CharField(max_length=100)),
                ('partners', models.ManyToManyField(related_name='p_name', to='home.CommunityPartner')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(max_length=20)),
                ('mission_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Missionarea')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='cpmission',
            name='mission_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Missionarea'),
        ),
        migrations.AddField(
            model_name='cpmission',
            name='partner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CommunityPartner'),
        ),
    ]
