# Generated by Django 2.1 on 2018-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180907_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypartner',
            old_name='status',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='address_line2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
