/*import '../LoginLogout/Login.cy'
import '../Register Partners/Partners.cy'
import '../Analytics/Reports/Focus_Area.cy'
import '../Analytics/Reports/Engagement_Types.cy'
import '../Analytics/Reports/Community_Partner.cy'
import '../Analytics/Reports/Project.cy'
import '../Analytics/Charts/Focus_Area.cy'
import '../Analytics/Charts/Engagement_Types.cy'
import '../Analytics/Charts/Focus_Area_Analysis.cy'
import '../Analytics/Charts/Network_Analysis.cy'
import '../Analytics/Charts/Partnership_Intensity_Analysis.cy'
import '../Analytics/Charts/Project_And_Partner_Trends.cy'
import '../Projects/All_Projects.cy'
import '../Projects/My_Projects.cy'
import '../Projects/Create_Project.cy'
import '../Resources/Community_Compass.cy'
import '../Resources/Office_Of_Engagement.cy'
import '../Resources/Share_Omaha.cy'
import '../LoginLogout/Logout.cy'
import '../PasswordReset/PasswordReset.cy'*/
import '../Campus Partner/LoginLogout/Login.cy'
import '../Campus Partner/PasswordReset/PasswordReset.cy'
import '../Campus Partner/Register Partners/Partners.cy'
import '../Campus Partner/Analytics/Reports/Focus_Area.cy'
import '../Campus Partner/Analytics/Reports/Engagement_Types.cy'
import '../Campus Partner/Analytics/Reports/Community_Partner.cy'
import '../Campus Partner/Analytics/Reports/Project.cy'
import '../Campus Partner/Analytics/Charts/Focus_Area.cy'
import '../Campus Partner/Analytics/Charts/Engagement_Types.cy'
import '../Campus Partner/Analytics/Charts/Focus_Area_Analysis.cy'
import '../Campus Partner/Analytics/Charts/Network_Analysis.cy'
import '../Campus Partner/Analytics/Charts/Partnership_Intensity_Analysis.cy'
//import '../Campus Partner/Analytics/Charts/Project_And_Partner_Trends.cy'

