# Generated by Django 2.1.1 on 2018-09-25 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPartnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('workphone', models.CharField(blank=True, help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cellphone', models.CharField(blank=True, help_text='Phone Number should be 10 digits', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contact_type', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Select', max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MissionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
