# Generated by Django 2.1.1 on 2018-09-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='partner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CommunityPartner'),
        ),
    ]
