# Generated by Django 2.1.1 on 2018-09-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='campuspartnercontact',
            name='partner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner'),
        ),
        migrations.AddField(
            model_name='contact',
            name='CommunityPartnerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.CommunityPartner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Select', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
