# Generated by Django 2.0 on 2018-10-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
                ('home', '0002_auto_20181007_1451'),
    ]

    operations = [
    ]
