# Generated by Django 2.1.1 on 2018-09-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180930_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='campus_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner'),
        ),
    ]
