# Generated by Django 2.1 on 2018-09-19 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20180918_2102'),
        ('home', '0002_contact_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPartnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.CampusPartner')),
            ],
        ),
    ]
