# Generated by Django 2.1.1 on 2019-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190321_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_Partner_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Campus Partner Snippet',
            },
        ),
        migrations.CreateModel(
            name='Campus_Partner_User_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Campus Partner User Snippet',
            },
        ),
        migrations.CreateModel(
            name='Community_Partner_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Community Partner Snippet',
            },
        ),
        migrations.CreateModel(
            name='Community_Partner_User_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Community Partner User Snippet',
            },
        ),
    ]
