# Generated by Django 2.1.1 on 2018-10-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180930_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cellphone',
            new_name='cell_phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='workphone',
            new_name='work_phone',
        ),
    ]
