# Generated by Django 2.1.1 on 2018-09-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_campuspartnercontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='partner_name',
            new_name='CommunityPartnerName',
        ),
        migrations.RemoveField(
            model_name='missionarea',
            name='mission_code',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Select', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
