# Generated by Django 2.1.1 on 2018-10-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='photo',
        ),
    ]
