# Generated by Django 2.1.1 on 2018-10-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181019_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
