# Generated by Django 2.1.1 on 2019-04-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_campus_partner_snippet_campus_partner_user_snippet_community_partner_snippet_community_partner_user_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Project_Report_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Public Project Report Snippet',
            },
        ),
    ]
