# Generated by Django 2.1.1 on 2018-09-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180924_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='CommunityPartnerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.CommunityPartner'),
        ),
    ]
