# Generated by Django 2.1.1 on 2018-10-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile_image/default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
