# Generated by Django 2.1.1 on 2019-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_private_project_report_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Private_Report_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Community Private Report Snippet',
            },
        ),
        migrations.CreateModel(
            name='Community_Public_Report_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Community Public Report Snippet',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(help_text='Write an introduction for the Site', max_length=255),
        ),
    ]
