# Generated by Django 2.1.1 on 2019-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_historicalcontact_historicaldatadefinition_historicalhouseholdincome_historicaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement_Types_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Engagement Types Chart Snippet',
            },
        ),
        migrations.CreateModel(
            name='Engagement_Types_Report_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Engagement Types Report Snippet',
            },
        ),
        migrations.CreateModel(
            name='Mission_Areas_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Mission Areas Charts Snippet',
            },
        ),
        migrations.CreateModel(
            name='Mission_Areas_Report_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Mission Areas Report Snippet',
            },
        ),
        migrations.AlterField(
            model_name='campus_partner_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='campus_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='community_partner_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='community_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='community_private_report_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='community_public_report_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='private_project_report_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='public_project_report_snippet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
