# Generated by Django 2.1.1 on 2019-04-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_all_projects_snippet_create_projects_snippet_my_projects_snippet_register_campus_partner_snippet_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
