# Generated by Django 2.1.1 on 2019-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190424_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Partner_Project_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Community Partner Project Snippet',
            },
        ),
        migrations.CreateModel(
            name='Create_Projects_Form_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Create Projects Form Snippet',
            },
        ),
        migrations.CreateModel(
            name='Login_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Login Snippet',
            },
        ),
        migrations.CreateModel(
            name='Logout_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Logout Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_Organizatiion_Profile_Contacts_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners Organization Profile Contacts Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_Organizatiion_Profile_Partners_Add_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners Organization Profile Partners Add Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_Organizatiion_Profile_Partners_Update_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners Organization Profile Partners Update Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_Organizatiion_Profile_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners Organization Profile Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_User_Profile_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners User Profile Snippet',
            },
        ),
        migrations.CreateModel(
            name='Partners_User_Profile_Update_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partners User Profile Update Snippet',
            },
        ),
        migrations.CreateModel(
            name='Password_Reset_Done_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Password Reset Done_Snippet',
            },
        ),
        migrations.CreateModel(
            name='Password_Reset_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Password Reset Snippet',
            },
        ),
        migrations.CreateModel(
            name='Register_Community_Partner_Form_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Register Community Partner Form Snippet',
            },
        ),
        migrations.AlterModelOptions(
            name='create_projects_snippet',
            options={'verbose_name': 'Create Projects Search Page Snippet'},
        ),
        migrations.AlterModelOptions(
            name='register_community_partner_snippet',
            options={'verbose_name': 'Register Community Partner Search Snippet'},
        ),
        migrations.AlterField(
            model_name='all_projects_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='campus_partner_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='campus_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='community_partner_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='community_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='community_private_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='community_public_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='create_projects_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='engagement_types_chart_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='engagement_types_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='mission_areas_chart_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='mission_areas_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='my_projects_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='private_project_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='public_project_report_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='register_campus_partner_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='register_campus_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='register_community_partner_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='register_community_partner_user_snippet',
            name='text',
            field=models.CharField(max_length=1250),
        ),
    ]
