
# Generated by Django 2.1.1 on 2019-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_historicalresource_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Address_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Issue Address Analysis  Charts Snippet',
            },
        ),
        migrations.CreateModel(
            name='TrendReport_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Trend Report Chart Snippet',
            },
        ),
    ]
