# Generated by Django 2.2.1 on 2019-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_issue_address_chart_snippet_trendreport_chart_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_Analysis_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Network Analysis Charts Snippet',
            },
        ),
        migrations.CreateModel(
            name='PartnershipIntensityAnalysis_Chart_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1250)),
            ],
            options={
                'verbose_name': 'Partnership Intensity Analysis Chart Snippet',
            },
        ),
    ]
