# Generated by Django 2.2.1 on 2019-11-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_network_analysis_chart_snippet_partnershipintensityanalysis_chart_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Other', 'Other')], default='Select', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Other', 'Other')], default='Select', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='work_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
