# Generated by Django 2.2.2 on 2019-11-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191101_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionarea',
            name='mission_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='missionarea',
            name='mission_image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
