# Generated by Django 2.2.7 on 2019-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191205_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionarea',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
