# Generated by Django 4.1.2 on 2022-11-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_historicaluniversity_logo_and_more'),
        ('home', '0021_alter_historicalcontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.university'),
        ),
    ]
