// New Test Scripts
import '../homepage/homepageCampusPartnerUser.cy'
import '../homepage/allFocusAreaCampusUser.cy'
import '../homepage/allFocusAreaAdminUser.cy'
import '../homepage/homepageAdministrator.cy'
import '../maps/legislativeDistrictMapsCampusPartner.cy'
import '../maps/communityPartnersMapsAdministratorUser.cy'
import '../maps/legislativeDistrictMapsAdmin.cy'
import '../analytics/reports/engagementTypesReportsCampusPartnerUser.cy'
import '../analytics/reports/CommunityPartnerReportsCampusUser.cy'
import '../analytics/reports/projectsReportsCampusUser.cy'
import '../analytics/charts/engagementTypesChartsCampusPartnerUser.cy'
import '../analytics/charts/focusAreaChartsCampusPartner.cy'
import '../analytics/charts/partnershipIntensityAnalysisChartsCampusPartnerUser.cy'
import '../analytics/charts/focusAreaChartsAdmin.cy'
import '../analytics/charts/projectAndPartnerTrendsChartsAdmin.cy'
import '../analytics/charts/partnershipIntensityAnalysisChartsAdminUser.cy'
import '../resources/resourcesAdminUser.cy'
import '../resources/resourcesCampusUser.cy'
import '../administrator/adminview/partners/campusPartner.cy'
import '../administrator/adminview/partners/campusPartnerUser.cy'
import '../administrator/adminview/partners/cecBuildingPartner.cy'
import '../administrator/adminview/partners/cecPartnerStatus.cy'
import '../administrator/adminview/partners/communityPartnerMissions.cy'
import '../administrator/adminview/partners/communityPartners.cy'
import '../administrator/adminview/partners/communityPartnerUsers.cy'
import '../administrator/adminview/partners/communityType.cy'
import '../administrator/adminview/partners/partnerStatus.cy'
import '../administrator/adminview/projects/academicYears.cy'
import '../administrator/adminview/projects/activityTypes.cy'
import '../administrator/adminview/projects/engagementActivityTypes.cy'
import '../administrator/adminview/projects/engagementTypes.cy'
import '../administrator/adminview/projects/missionSubCategory.cy'
import '../administrator/adminview/projects/projects.cy'
import '../administrator/cms/cms.cy'
import '../campusPartner/profile/profileDetails.cy'
import '../projects/allProjectsAdminUser.cy'
import '../projects/createProjectsAdminUser.cy'
import '../projects/myDraftAdministrator.cy'
import '../projects/myProjectsAdminUser.cy'


// Data-cy elements added in
import '../homepage/homepagePublicUser.cy'
import '../homepage/allFocusAreaPublicUser.cy'
import '../analytics/reports/engagementTypesReportsPublicUser.cy'
import '../projects/myDraftCampusPartnerUser.cy'

//hardcoded link update done in
import '../registerPartners/registerCampusPartnerCampusPartnerUser.cy'
import '../projects/myDraftCampusPartnerUser.cy'
import '../analytics/reports/focusAreaReportsPublicUser.cy'
import '../analytics/reports/focusAreaReportsCampusPartnerUser.cy'