# Generated by Django 2.1.1 on 2018-11-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181121_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(max_length=13),
        ),
    ]
