# Generated by Django 2.1.1 on 2018-09-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='client',
        ),
    ]
