/// <reference types="cypress"/>
import user from "../../support/commands.js";
describe('audit logs admin user test', () => {
beforeEach(() => {
    cy.on('uncaught:exception', (err) => {
      if(err.message.includes('is not a function') || err.message.includes('is not defined') || err.message.includes('reading \'addEventListener\'') || err.message.includes('null (reading \'style\')'))
      {
        return false
      }
    })
    cy.fixture("datareports").then(function(data) {
      this.data = data
    })
    cy.loginAdminUser(user) // Admin User is logged in before the test begins
    cy.visit(Cypress.env('baseUrl'))
  })
    //Check navigation to Engagement types charts
    it('validate audit logs exist', function () {
        cy.get('[data-cy="administrator"]').should('exist').click()
        cy.get('[data-cy="auditlogs"]').should('exist').click()
    })
    it('test show more button', function () {
        cy.get('[data-cy="administrator"]').click()
        cy.get('[data-cy="auditlogs"]').click()
        cy.get('[data-cy="show-more"]').should('exist').click()
        cy.get('[data-cy="show-more-projmission"]').should('exist').click()
        cy.get('[data-cy="show-more-projcampus"]').should('exist').click()
        cy.get('[data-cy="show-more-projcomm"]').should('exist').click()
        cy.get('[data-cy="show-more-campus"]').should('exist').click()
        cy.get('[data-cy="show-more-comm"]').should('exist').click()
        cy.get('[data-cy="show-more-commiss"]').should('exist').click()
        cy.get('[data-cy="show-more-user"]').should('exist').click()
    })
    it('test recent changes to project', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more"]').should('exist').click()
          .get(`select[name="example_length"]`).select('10').should('exist')
          .get(`select[name="example_length"]`).select('25').should('exist')
          .get(`select[name="example_length"]`).select('50').should('exist')
          .get(`select[name="example_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('be.visible')
          .get('a').contains('Next').should('be.visible')
          .get('[data-cy="example"]').should('be.visible')
          .get('[data-cy = "name_project"]').should('exist').click()
          .get('[data-cy="update_time_project"]').should('exist').click()
          .get('[data-cy="changed_by_project"]').should('exist').click()
          .get('[data-cy="description_project"]').should('exist').click()
    })
    it('test recent changes to project mission', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-projmission"]').should('exist').click()
          .get(`select[name="example1_length"]`).select('10').should('exist')
          .get(`select[name="example1_length"]`).select('25').should('exist')
          .get(`select[name="example1_length"]`).select('50').should('exist')
          .get(`select[name="example1_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example1"]').should('be.visible')
          .get('[data-cy ="name_project_projmission"]').should('exist').click()
          .get('[data-cy="mission-type_projmission"]').should('exist').click()
          .get('[data-cy="mission_area_projmission"]').should('exist').click()
          .get('[data-cy="update_time_projmission"]').should('exist').click()
          .get('[data-cy="changed_by_projmission"]').should('exist').click()
          .get('[data-cy="description_projmission"]').should('exist').click({force: true})
    })
    it('test recent changes to project campus partner', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-projcampus"]').should('exist').click()
          .get(`select[name="example2_length"]`).select('10').should('exist')
          .get(`select[name="example2_length"]`).select('25').should('exist')
          .get(`select[name="example2_length"]`).select('50').should('exist')
          .get(`select[name="example2_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example2"]').should('be.visible')
          .get('[data-cy ="name_project_projcampus"]').should('exist').click()
          .get('[data-cy="campus_partner_name_projcampus"]').should('exist').click()
          .get('[data-cy="update_time_projcampus"]').should('exist').click()
          .get('[data-cy="changed_by_projcampus"]').should('exist').click()
          .get('[data-cy="description_projcampus"]').should('exist').click({force:true})
    })
    it('test recent changes to project community partner', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-projcomm"]').should('exist').click()
          .get(`select[name="example3_length"]`).select('10').should('exist')
          .get(`select[name="example3_length"]`).select('25').should('exist')
          .get(`select[name="example3_length"]`).select('50').should('exist')
          .get(`select[name="example3_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example3"]').should('be.visible')
          .get('[data-cy ="name_project_projcomm"]').should('exist').click()
          .get('[data-cy="community_partner_name_projcomm"]').should('exist').click()
          .get('[data-cy="update_time_projcomm"]').should('exist').click()
          .get('[data-cy="changed_by_projcomm"]').should('exist').click()
          .get('[data-cy="description_projcomm"]').should('exist').click()
    })
    it('test recent changes to campus partner', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-campus"]').should('exist').click()
          .get(`select[name="example9_length"]`).select('10').should('exist')
          .get(`select[name="example9_length"]`).select('25').should('exist')
          .get(`select[name="example9_length"]`).select('50').should('exist')
          .get(`select[name="example9_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example9"]').should('be.visible')
          .get('[data-cy ="campus_partner_name_campus"]').should('exist').click()
          .get('[data-cy="update_time_campus"]').should('exist').click()
          .get('[data-cy="changed_by_campus"]').should('exist').click()
          .get('[data-cy="description_campus"]').should('exist').click({force:true})
    })
    it('test recent changes to community partner', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-comm"]').should('exist').click()
          .get(`select[name="example5_length"]`).select('10').should('exist')
          .get(`select[name="example5_length"]`).select('25').should('exist')
          .get(`select[name="example5_length"]`).select('50').should('exist')
          .get(`select[name="example5_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example5"]').should('be.visible')
          .get('[data-cy ="community_partner_name_comm"]').should('exist').click()
          .get('[data-cy="update_time_comm"]').should('exist').click()
          .get('[data-cy="changed_by_comm"]').should('exist').click()
          .get('[data-cy="description_comm"]').should('exist').click()
    })
    it('test recent changes to community partner missions', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-commiss"]').should('exist').click()
          .get(`select[name="example6_length"]`).select('10').should('exist')
          .get(`select[name="example6_length"]`).select('25').should('exist')
          .get(`select[name="example6_length"]`).select('50').should('exist')
          .get(`select[name="example6_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example6"]').should('be.visible')
          .get('[data-cy ="community_partner_name_commiss"]').should('exist').click()
          .get('[data-cy="mission_area_commiss"]').should('exist').click()
          .get('[data-cy="update_time_commiss"]').should('exist').click()
          .get('[data-cy="changed_by_commiss"]').should('exist').click()
          .get('[data-cy="description_commiss"]').should('exist').click({force:true})
    })
    it('test recent changes to contacts', function () {
        cy.get('[data-cy="administrator"]').click()
          .get('[data-cy="auditlogs"]').click()
          .get('[data-cy="show-more-user"]').should('exist').click()
          .get(`select[name="example7_length"]`).select('10').should('exist')
          .get(`select[name="example7_length"]`).select('25').should('exist')
          .get(`select[name="example7_length"]`).select('50').should('exist')
          .get(`select[name="example7_length"]`).select('100').should('exist')
          .get('a').contains('Previous').should('not.be.empty')
          .get('a').contains('Next').should('not.be.empty')
          .get('[data-cy="example7"]').should('be.visible')
          .get('[data-cy ="contact_name"]').should('exist').click()
          .get('[data-cy="update_time_user"]').should('exist').click()
          .get('[data-cy="changed_by_user"]').should('exist').click()
          .get('[data-cy="description-user"]').should('exist').click()
    })
})
