# Generated by Django 2.1.1 on 2019-04-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_historicalcollege_historicalcourse_historicaldepartment_historicaleducationsystem_historicaluniversi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('college_name',)},
        ),
    ]
