# Generated by Django 2.1.1 on 2018-10-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20181008_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=30),
        ),
    ]
