# Generated by Django 2.1.1 on 2018-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20181009_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='college',
            new_name='college_name',
        ),
    ]
