# Generated by Django 4.1.1 on 2022-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190420_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcollege',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical college', 'verbose_name_plural': 'historical colleges'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course', 'verbose_name_plural': 'historical courses'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical department', 'verbose_name_plural': 'historical departments'},
        ),
        migrations.AlterModelOptions(
            name='historicaleducationsystem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical education system', 'verbose_name_plural': 'historical education systems'},
        ),
        migrations.AlterModelOptions(
            name='historicaluniversity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical University', 'verbose_name_plural': 'historical Universities'},
        ),
        migrations.AlterField(
            model_name='historicalcollege',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleducationsystem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
