# Generated by Django 4.1.2 on 2022-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_historicalcollege_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversity',
            name='logo',
            field=models.TextField(default='default.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='primary_color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='secondary_color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='university',
            name='primary_color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='secondary_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
