# Generated by Django 4.1.2 on 2022-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_historicaluniversity_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversity',
            name='subdomain',
            field=models.CharField(db_index=True, default='Set Subdomain of tenant, i.e. unomaha', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='subdomain',
            field=models.CharField(default='Set Subdomain of tenant, i.e. unomaha', max_length=255, unique=True),
        ),
    ]
