# Generated by Django 4.1.2 on 2022-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_historicaluniversity_subdomain_university_subdomain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluniversity',
            name='logo',
            field=models.TextField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to=''),
        ),
    ]
