# Generated by Django 4.1.7 on 2023-02-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_historicaluniversity_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluniversity',
            name='logo',
            field=models.CharField(default='https://www.unomaha.edu/_files/images/logo-subsite-o-2.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='primary_color',
            field=models.CharField(default='#0a0a0a', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='secondary_color',
            field=models.CharField(default='#D71920', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.CharField(default='https://www.unomaha.edu/_files/images/logo-subsite-o-2.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='primary_color',
            field=models.CharField(default='#0a0a0a', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='secondary_color',
            field=models.CharField(default='#D71920', max_length=255),
        ),
    ]
